server:
  port: 8080
spring:
  application:
    name: example
  cloud:
    nacos:
      config:
        server-addr: 47.98.191.6:8848
        namespace: test
        file-extension: yaml
      discovery:
        server-addr: 47.98.191.6:8848
        namespace: test